import Head from 'next/head'
import Link from 'next/link';
import Header from '../components/header'
import Date from '../../components/date';
import { getSortedPostsData, Posts } from '../../lib/posts';
import styles from '@/styles/home.module.scss'

export async function getStaticProps() {
    const allPostsData = getSortedPostsData();
    return {
      props: {
        allPostsData,
      },
    };
  }

interface AllPosts {
    allPostsData: Posts
}

export default function Blog(props: AllPosts) {
  const {allPostsData} = props

    return (
        <>
          <Head>
            <title>Kevin Minutti</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="favicon.ico" />
          </Head>
          <Header/>
          <main className={styles.main}>
          <section >
                  <ul className="list">
                    {allPostsData.map(({ id, date, title }) => (
                      <li className="listItem" key={id}>
                        <small className="date">
                          <Date dateString={date} />
                        </small>
                        <br />
                        <Link href={`/posts/${id}`}>
                          <h3>{title}</h3></Link>
                      </li>
                    ))}
                  </ul>
          </section>
      </main>
    </>
    )
}

