import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kevin Minutti</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
              <code className={styles.code}>Kevin Minutti</code>
        </div>
        <div className={styles.center}>
              <Image
                className={styles.portrait}
                src="/../public/portrait.png"
                alt="portrait"
                width={360}
                height={225}
                priority
              />
        </div>
        <div className={styles.center}>
          <div className={styles.description}>
          <code>I like to code mostly in Python, Go, TypeScript and C++.</code>

          </div>
        </div>

          <div className={styles.grid}>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <p className={inter.className}>
                <code>What I'm up to </code><span>-&gt;</span>
              </p>
            </a>

            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <p className={inter.className}>
                
                <code>My writing </code><span>-&gt;</span>
              </p>
            </a>

            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <p className={inter.className}>
              <code>Reading list </code><span>-&gt;</span>
              </p>
            </a>
          </div>
      </main>
    </>
  )
}
