import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function ReadingList() {
    return (
        <>
          <Head>
            <title>Kevin Minutti</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="favicon.ico" />
          </Head>
          <main>
            <p><big>Reading List</big></p>
            <div>
            <p><span>01.02.23    | </span>A Mind for Numbers - Barbara Oakley</p>
            <p><span>01.09.23    | </span>Hackers - Steven Levy</p>
            <p><span>01.16.23   | </span>Previous Week Continued</p>
            </div>
         </main>
    </>
    )
}